### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by deters** [vladdenisov/ytmusic-api#6]
The search endpoint is not working right now... 

let COOKIE = 'yyy';
let USER_ID = 'xxx';

import { YTMUSIC } from 'ytmusic';

const api = new YTMUSIC(COOKIE, { userID: USER_ID })

api.search('Hey Jude', { filter: 'songs' })
    .then(console.log)
    .catch(console.error)

------ result:

TypeError: Cannot read property 'contents' of undefined
    at /home/deters/workspace/yti/node_modules/ytmusic/dist/lib/endpoints/Search.js:111:66
    at step (/home/deters/workspace/yti/node_modules/ytmusic/dist/lib/endpoints/Search.js:52:23)
    at Object.next (/home/deters/workspace/yti/node_modules/ytmusic/dist/lib/endpoints/Search.js:33:53)
    at fulfilled (/home/deters/workspace/yti/node_modules/ytmusic/dist/lib/endpoints/Search.js:24:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[nodemon] clean exit - waiting for changes before restart

**Comment by deters** [comment]
I made a pull request to fix this:
https://github.com/vladdenisov/ytmusic-api/pull/7
